#ifndef CONSTANT_H
#define CONSTANT_H

#define CELL_SIZE 50
#define MAP_INIT_SPACE_WIDTH 100
#define MAP_INIT_SPACE_HEIGHT 100
#define VIEW_WIDTH 1280
#define VIEW_HEIGHT 720
#define SCENE_WIDTH 2000
#define SCENE_HEIGHT 1000
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define MAINMENU_WIDTH 750
#define MAINMENU_HEIGHT 422
#define ELEMENTS_NUM 6

#endif
